version: 0.0
os: linux
files:
  - source: /
    destination: "/var/www/html/superkid/tes-github"
permissions:
  - object: /var/www/html/superkid/tes-github
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 775
    type:
      - directory
      - file
